import {
  type StageFunctionHelpers,
  type StageFunction,
} from "../stage-function.js";

const stageFn_generateSemanticContextQueries: StageFunction = async (
  helpers: StageFunctionHelpers
  // eslint-disable-next-line @typescript-eslint/require-await
) => {
  // TODO
  //   Context hooks are generated by an LLM. These are distinct ideas, sentences, and
  // questions along the lines of, "What do I need to know in order to complete this task?"
  helpers.endStage();
};

export default stageFn_generateSemanticContextQueries;
