yarnPath: .yarn/releases/yarn-3.5.0.cjs
packageExtensions:
  aframe-forcegraph-component@*:
    peerDependencies:
      three: "*"
  3d-force-graph-ar@*:
    peerDependencies:
      three: "*"
  3d-force-graph-vr@*:
    peerDependencies:
      three: "*"
  react-force-graph@*:
    peerDependencies:
      three: "*"
  weaviate-ts-client2@*:
    peerDependencies:
      graphql: "*"
  "@clerk/themes@*":
    peerDependencies:
      tslib: "*"
