---
version: "3.4"
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.18.3
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_KEY}
      AUTHENTICATION_APIKEY_USERS: "doesnt-matter"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "backup-filesystem"
      CLUSTER_HOSTNAME: "node1"
      BACKUP_FILESYSTEM_PATH: ${WEAVIATE_BACKUP_DIR}
    volumes:
      - /var/weaviate:/var/lib/weaviate
